config/routes.rb
Rails.application.routes.draw do
  get 'scan/new'
  resources :books
  resources :loans
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :reviews
  get "about", to: "pages#about"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root to: "books#index"

end

app/models/book.rb
class Book < ApplicationRecord
  validates :ISBN, presence: true
  validates :author, presence: true
  validates :title, presence: true
  has_many :loans
  has_many :reviews
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  require 'json'
  require 'net/http'
  require 'uri'
  
  # GET /books or /books.json
  
  def index
    @books = Book.all
    book_ids = Book.pluck(:id)
    @book = Book.find(book_ids.sample)
    @reviews = Review.where(book_id: @book.id)
    @stars = @book.reviews.average(:stars)


  end

  # GET /books/1 or /books/1.json
  def show
    @pagy, @reviews = pagy(Review.where(book_id: @book.id))
    # @average_rating = @reviews.stars.sum(0.0) / @reviews.count
  end

  # GET /books/new
  def new
   @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.build(book_params) if manually_adding?
    @book = book_from_scan(params[:isbn]) if searching_by_isbn?

    respond_to do |format|
      if @book == false
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      elsif @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def correct_user
    @book = current_user.books.find_by(id: params[ :id])
    redirect_to books_path, notice: "Not authorized to edit this book" if @book.nil?
  end

  def searching_by_isbn?
    params[:commit] == "Search"
  end

  def manually_adding?
    params[:commit] == "Create Book"
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:id).permit(:title, :author, :cover_text, :short_description, :cost, :collection, :case, :shelf, :ISBN)
  end

  def book_from_scan(isbn)

    isbn_link = "https://openlibrary.org/api/books?bibkeys=ISBN:"+isbn+"&jscmd=data&format=json"
    uri = URI.parse(isbn_link)
    response = Net::HTTP.get_response(uri)
    parsed_json = JSON.parse(response.body)
    info = parsed_json["ISBN:"+isbn]

    if info.nil?
      @book = Book.new(title: info['title'], authors: authors, publisher: publishers,
        edition: info['publish_date'], pages: info['number_of_pages'], isbn: isbn,
        cover_link: info['cover']['medium'])
    else
      authors = join_field(info['authors'])
      publishers = join_field(info['publishers'])
      @book = Book.new
      @book = Book.update(
        title: info['title'],
        authors: authors,
        publisher: publishers,
        edition: info['publish_date'],
        pages: info['number_of_pages'],
        isbn: isbn,
        cover_link: info['cover']['medium'],
        user_id: current_user)
    end
  end

  def join_field(field)
    field.map do |a|
      "#{a['name']}"
    end.join
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<!--
<div id="<%= dom_id book %>">
<tr>
  <td><%= link_to book.title, book %></td>
  <td><%= book.author %></td>
  <td><%= book.ISBN %></td>
  <td><%= book.cover_text %></td>
  <td><%= book.short_description %></td>
  <td><%= book.cost %></td>
  <td><%= book.collection %></td>
  <td><%= book.case %></td>
  <td><%= book.shelf %></td>
</tr>
</div>
-->
<div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-sm-8 col-lg-6">
            <!-- Section Heading-->
            <div class="section_heading text-center wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
              <h3>Writing Center <span> Diversity Collection</span></h3>
              <p>This would make a very good place for a description &amp; random assortment of books in the collection.</p>
              <div class="line"></div>
            </div>
          </div>
        </div>
        <div class="row">

          <!-- Single Book -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="book_card_profile wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
              <!-- Book Thumb -->
              <div class="book_thumb"><%= image_tag (@book.cover_link), class: "img rounded-top", style: "width:200px;" %>
                <!-- Review Section -->
                <div class="social-info"><% @reviews.average(:stars).floor.times do |star| %><i class="fa fa-star checked" stlye="color:orange;"></i><% end %></div>
              </div>
              <!-- Team Details-->
              <div class="book_card_details_info">
                <h6><%= link_to book.title, book %></h6>
                <p class="designation"><%= book.author %></p>
              </div>
              <!-- Button trigger modal
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                Launch demo modal
              </button> -->

              <!-- Modal -->
              <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ...
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                  </div>
                </div>
              </div>

              </div>
            </div>
          </div>

        </div>
      </div>

app/views/books/_form.html.erb
<div class="mx-auto" style="width: 400px">
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-2">
    <% form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control", placeholder: :title %>
  </div>

  <div class="field form-group mb-2">
    <% form.label :author, style: "display: block" %>
    <%= form.text_field :author, class: "form-control", placeholder: :author %>
  </div>

  <div class="field form-group mb-2">
    <% form.label :cover_text, style: "display: block" %>
    <%= form.text_field :cover_text, class: "form-control", placeholder: :cover_text %>
  </div>

  <div class="field form-group mb-2">
    <% form.label :short_description, style: "display: block" %>
    <%= form.text_field :short_description, class: "form-control", placeholder: :short_description %>
  </div>

  <div class="field form-group mb-2">
    <% form.label :cost, style: "display: block" %>
    <%= form.text_field :cost, class: "form-control", placeholder: :cost %>
  </div>

  <div class="field form-group mb-2">
    <% form.label :ISBN, style: "display: block" %>
    <%= form.text_field :ISBN, class: "form-control", placeholder: "ISBN 10 or 13" %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-outline-primary', :name => 'commit' %>
  </div>
<% end %>
</div>

app/views/books/_scan.html.erb
  <%= form_with model: @book do |form| %>
    <%= form.label :isbn, "Enter ISBN 10 or 13: ", class: "form-label" %>
    <%= number_field_tag 'isbn', class: "form-control"  %>
    <%= form.submit "Search", commit: 'isbn', class: 'btn btn-primary btn-sm' %>
  <% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<% if user_signed_in? %>
<!--
<table class ="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Author(s)</th>
      <th>Publisher</th>
      <th>Edition</th>
      <th>Pages</th>
    </tr>
  </thead>
  <tbody>

  <% @books.each do |book| %>
        <%= render book %>
  <% end %>
  
  </tbody>
</table>
-->
<%= link_to "New book", new_book_path, class: "btn btn-secondary" %>

<% else %>
<h1>Welcome to the bookshelf!</h1>
Sign in or sign up to get stacking!

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<% end %>

app/views/books/new.html.erb
<div class="row p-5">

  <div class="col-sm-6">
    <div class="card border-light">
      <div class="card-body">
        <h5 class="card-title">Add manually...</h5>
         <%= render "form", book: @book %>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="card border-light">
      <div class="card-body">
        <h5 class="card-title">Or by ISBN...</h5>
          <%= render "scan", book: @book %>
      </div>
    </div>
  </div>

</div>

<br/><br/>
<div>
  <% link_to "Back to books", books_path, class: 'btn btn-dark' %>
</div>
<%= @book.inspect %>

app/views/books/show.html.erb
<div class="container"style="width:48rem;">
  <div class="card mt-3 mb-3 shadow-lg">
    <div class="row g-0">
      <div class="col-md-4">
        <%= image_tag (@book.cover_link), class: 'img-fluid rounded-start' %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <div class="card-header">
            <h3> <%= @book.title %> </h3>
            <h5> <%= @book.author %> </h5>
          </div>
          <div class="card-text">
            <span>Rating</span><span>(number of reviews)</span>
            <p class="card-text text-muted"> <%= @book.short_description %> </p>
            <p class="card-text text-muted"> <%= @book.collection %>  |  <%= @book.shelf %> </p>
            <p class="card-text text-muted"> ISBN: <%= @book.ISBN %> </p>
            <p><%= link_to "Back to books", books_path, class: "btn btn-dark" %></p>
            <% if !current_user.nil? %>
              <% if current_user.admin == true %>
                <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-secondary" %>
              <% end %>
              <% if current_user.admin == false %>
                <%= link_to "Review this book", new_review_path(@book), class: "btn btn-secondary" %>
              <% end %>
              <% if current_user.admin == false %>
                <%= link_to "Borrow this book", new_loan_path(@book), class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% if !current_user.nil? %>
  <% if current_user.admin == true %>
      <div class="text-center">
        <p><em>Warning:</em> Deletion cannot be undone</p>
        <p>
          <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Ok, I want to delete this book
          </button>
        </p>
        <div class="collapse" id="collapseExample">
            <%= button_to "Destroy this book", @book, method: :delete, class: 'btn btn-outline-danger btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<div class="row">
  <div class="col">
    <span style="font-size:40px;"><%= @book.reviews.average(:stars) %></span><span>/5</span>
  </div>
  <div class="col justify-content-right">
    <%= @book.reviews.count %> reviews
  </div>
</div>

<div class="row row-cols-1 row-cols-md-2 g-4">
  
  <% @reviews.order("created_at desc").each do |review| %>
    <%= render partial: "/reviews/review", locals: {review: review} %>
  <% end %>
</div>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>