config/routes.rb
Rails.application.routes.draw do
  get 'scan/new'
  resources :books
  resources :loans
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :reviews
  get "about", to: "pages#about"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root to: "books#index"

end

app/models/loan.rb
class Loan < ApplicationRecord
    validates :book_id, presence: true
    validates :user_id, presence: true
    validates :created_at, presence: true
    belongs_to :user
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]

  # get user
  # verify that book is available


  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1 or /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans or /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to loan_url(@loan), notice: "Loan was successfully created." }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to loan_url(@loan), notice: "Loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.fetch(:loan, {})
    end

    def set_book
      @book = Book.find(params[:id])
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_with(model: loan) do |form| %>
  <% if loan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# These attributes should be hidden, but need to be present when a new loan is created %>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :user_id, value: current_user.id, type: :hidden %>
  </div>

    <div class="field form-group">
    <%= form.number_field :book_id, id: :books_id, value: book.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/_loan.html.erb
<div id="<%= dom_id loan %>">
</div>

app/views/loans/edit.html.erb
<h1>Editing loan</h1>

<%= render "form", loan: @loan %>

<br>

<div>
  <%= link_to "Show this loan", @loan %> |
  <%= link_to "Back to loans", loans_path %>
</div>

app/views/loans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Loans</h1>

<div id="loans">
  <% @loans.each do |loan| %>
    <%= render loan %>
    <p>
      <%= link_to "Show this loan", loan %>
    </p>
  <% end %>
</div>

<%= link_to "New loan", new_loan_path %>

app/views/loans/new.html.erb
<h1>New loan</h1>

<%= render "form", loan: @loan %>

<br>

<div>
  <%= link_to "Back to loans", loans_path %>
</div>

app/views/loans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @loan %>

<div>
  <%= link_to "Edit this loan", edit_loan_path(@loan) %> |
  <%= link_to "Back to loans", loans_path %>

  <%= button_to "Destroy this loan", @loan, method: :delete %>
</div>